#https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#web.servlet.spring-mvc.static-content
#只要静态资源放在类路径下 /static or /META-INF/resources or /public or /resources
#访问: 当前根路径+静态资源名
# 静态资源映射的是 /**
# 请求进来,先去找Controller看能否处理,不能处理的所有请求又都交给静态资源处理器.静态资源又会去上述目录找,如果能找到则返回,如果找不到则报404

#静态资源访问前缀(默认无前缀)
#spring:
#  mvc:
#    static-path-pattern: /res/**
#在当前项目 + static-path-pattern + 静态资源名 = 静态资源文件夹 下找静态资源
#注意: 源码里欢迎页是写死的路径,即org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping.WelcomePageHandlerMapping
#要做两个判断
#1. welcomePage.isPresent() 欢迎页是否存在,这里idea会有bug,需要在修改index位置后用maven重新编译才会生效
#2. "/**".equals(staticPathPattern),判断staticPathPattern是否是/**
# 结论:
#1. 要使用欢迎页功能,必须是/**
#2. 如果非要自定义静态变量的前缀，访问静态资源是 当前项目 + static-path-pattern + 静态资源名 = 静态资源文件夹下找

spring:
  mvc:
#    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true  #配置成false会禁用所有静态资源

  #默认的静态资源路径
  resources:
    static-locations: [classpath:/haha/]
    add-mappings: true
    cache:
      period: 11000

#自动映射 /webjars/**
#访问地址：http://localhost:8080/webjars/jquery/3.5.1/jquery.js   后面地址要按照依赖里面的包路径
#自动映射


#
#spring.mvc.hiddenmethod.filter

