spring:
  datasource:
    url: jdbc:mysql://10.10.3.106:3306/ia
    username: root
    password: mysql
#    url: jdbc:mysql://localhost:3306/ssm
#    username: root
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      max-active: 100
  jdbc:
    template:
      query-timeout: 3