spring:
  datasource:
#    url: jdbc:mysql://10.10.3.106:3306/x_account
#    username: root
#    password: mysql
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


    druid:
      stat-view-servlet:                #监控页配置
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false
      web-stat-filter:                  #web监控
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      aop-patterns: com.ncamc.admin.*   #项目监控
      filters: stat,wall,slf4j          #所有开启的功能
      filter:
        stat: #sql监控
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false


  jdbc:
    template:
      query-timeout: 3

  redis:
    host: r-2zex2z3sje260hmeqqpd.redis.rds.aliyuncs.com
    port: 5000
    #默认是lettuce
    #JedisConnectionConfiguration中条件判断,若这里的client-type为jedis则生效
    client-type: jedis
    password: ABC123abc

#使用MyBatisPlus则下面的规则失效
#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration: #替换掉mybatis全局配置文件
#    map-underscore-to-camel-case: true

#与监控有关的配置都以management开头
management:
  endpoints:
    enabled-by-default: false  #默认开启所有监控端点  true
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true